version: 2.1

orbs:
  postgres: onehq/postgres@1.1.0

commands:
  yarn-install:
    description: Install cached yarn packages
    steps:
      - restore_cache:
          keys: ['v2-{{ checksum "yarn.lock" }}']
      - run: yarn config set yarn-offline-mirror ~/.cache/yarn
      - run: yarn install --frozen-lockfile

  npm-login:
    description: Set npm login
    steps:
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

  yarn-save-cache:
    description: Save yarn packages cache
    steps:
      - save_cache:
          key: v2-{{ checksum "yarn.lock" }}
          paths: ['~/.cache']

jobs:
  test:
    docker:
      - image: circleci/node:10
      - image: postgres:11
        environment:
          POSTGRES_DB: example
          POSTGRES_USER: example-admin
          POSTGRES_PASSWORD: example-pass
    steps:
      - checkout
      - run:
          name: 'Update Submodules'
          command: |
            git submodule sync
            git submodule update --init
      - yarn-install
      - yarn-save-cache
      - run: yarn build --concurrency 1
      - postgres/install_postgres_client
      - run:
          name: 'Run install scripts for examples'
          command: |
            psql postgres://example-admin:example-pass@localhost:5432/example < examples/petstore/init.sql
            psql postgres://example-admin:example-pass@localhost:5432/example < examples/split/init.sql
      - run: yarn test

  publish:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - yarn-install
      - run: yarn build --concurrency 1
      - npm-login
      - run: git config user.email "ovotech-ci@ovoenergy.com"
      - run: git config user.name "Ovotech CI"
      - run: yarn lerna publish from-package --yes

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore: master
  deploy:
    jobs:
      - test:
          filters:
            branches:
              only: master
      - publish:
          requires:
            - test
