openapi: '3.0.0'
info:
  title: 'Simple Example'
  version: 1.0.0
paths:
  /user/{id}:
    get:
      security:
        - MySecurity: []
      parameters:
        - name: 'id'
          in: 'path'
          required: true
          schema:
            type: 'string'
            pattern: '\d+'
      responses:
        200:
          description: 'User'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
components:
  # << security
  securitySchemes:
    MySecurity:
      type: http
      scheme: bearer
  # security
  schemas:
    UserResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
