openapi: 3.0.2
info:
  description: 'Boost Core API getBalance functionality'
  version: '0.1.0'
  title: 'Boost Core API - get balance'

# servers:
#   - url: todo
#     description: todo

paths:
  /.well-known/health-check:
    get:
      summary: Returns OK if the service is running and healthy
      responses:
        200:
          $ref: '#/components/responses/Healthy'
        500:
          $ref: '#/components/responses/ServerError'

  /v1/{accountID}/balance/last-known:
    post:
      summary: Test Post
      parameters:
        - in: path
          name: accountID
          required: true
          schema:
            type: string
            pattern: '^\d{1,12}$'
          description: The Gentrack account ID to get the balance for.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LastKnwonRequest'
      responses:
        200:
          $ref: '#/components/responses/Success'
        400:
          $ref: '#/components/responses/BadRequest'

    get:
      summary: Returns information about the last known balance(s) for an account.
      parameters:
        - in: path
          name: accountID
          required: true
          schema:
            type: string
            pattern: '^\d{1,12}$'
          description: The Gentrack account ID to get the balance for.
      responses:
        200:
          $ref: '#/components/responses/Success'
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/ServerError'
        502:
          $ref: '#/components/responses/BadGateway'
        504:
          $ref: '#/components/responses/GatewayTimeout'

components:
  responses:
    Healthy:
      description: State of the service
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Healthy'
    Success:
      description: Balance information
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BalanceResponseEntity'
    BadRequest:
      description: Bad request - user input error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HttpErrorResponse'
    NotFound:
      description: Balance could not be found for specified account.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HttpErrorResponse'
    ServerError:
      description: Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HttpErrorResponse'
    BadGateway:
      description: Data source provided invalid response.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HttpErrorResponse'
    GatewayTimeout:
      description: Information not returned quickly enough by data source.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HttpErrorResponse'

  schemas:
    Healthy:
      type: object
      properties:
        healthy:
          type: boolean
      required:
        - healthy
    BalanceResponseEntity:
      oneOf:
        - $ref: '#/components/schemas/PAYGPlusBalanceObjectEntity'
    PAYGPlusBalanceObjectEntity:
      description: Balances for a PAYG+ customer.
      type: object
      properties:
        singleWalletBalance:
          $ref: '#/components/schemas/SingleWalletBalanceEntity'
    LastKnwonRequest:
      description: Test Stuff
      type: object
      properties:
        value:
          type: integer
          example: 123000
        other:
          type: string
      required:
        - value
        - other

    BaseBalanceEntity:
      type: object
      properties:
        value:
          description: The value of the balance. 1/1000ths of a penny. eg. 1000=1p, 100000=£1
          type: integer
          format: int32
          example: 123000
        effectiveAt:
          description: The last transaction date-time that updated the balance.
          type: string
          format: date-time
          example: '2019-01-30T17:32:28Z'
        updatedAt:
          description: The date-time that the balance was updated.
          type: string
          format: date-time
          example: '2019-01-30T17:53:28Z'
      required:
        - value
    SingleWalletBalanceEntity:
      allOf:
        - $ref: '#/components/schemas/BaseBalanceEntity'
        - type: object
          properties:
            fuelType:
              description: The fuel that the balance is for.
              type: string
              enum: [DualFuel]
          required:
            - fuelType

    HttpErrorResponse:
      type: object
      properties:
        code:
          description: An error code.
          type: integer
          format: int32
          minimum: 1
        message:
          description: Information about the error.
          type: string
      required:
        - message
